name: Build and Test Package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: Fooji/create-aws-profile-action@v1
        with:
          profile: default
          region: us-west-2
          key: mock_access_key
          secret: mock_secret_key
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 black
          python -m pip install poetry
      - name: Lint with black and flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          black --check .
      - name: Build
        run: |
          poetry install --system
      - name: Test
        run: |
          python -m pytest aws_cost_mutilator/tests.py
